#!/usr/bin/env bash

# Path to keepass database
if [ -f /mnt/maciej/Passwords.kdbx ]
then
  database="/mnt/maciej/Passwords.kdbx"
elif [ -f /mnt/sftp/Passwords.kdbx ]
then
  database="/mnt/sftp/Passwords.kdbx"
else
  notify-send "keepassxc" "Please check if network shares are mounted" &&
  exit
fi

# Path to gpg encpypted file containing password for the database
passgpg="$HOME/.local/pass.gpg"

[[ ! -e "$database" ]] && notify-send "keepassxc" "Please check if the database variable is set properly" && exit
[[ ! -e "$passgpg" ]] && notify-send "keepassxc" "Please check if the passgpg variable is set properly" && exit

# Customize dmenu
dmenu="dmenu -i -l 20"

# Timeout after which clipboard will be cleared
timeout=15

# Decrypt the password
pass="$(gpg -d ${passgpg} 2> /dev/null)"

# Extract entries list from the database
entry=$(echo ${pass} | keepassxc-cli ls "${database}" 2> /dev/null | \
    eval $dmenu)

# Exits if no entry is selected
[[ $entry ]] || exit

# Checks if the entry selected is a group or a regular entry. If it is a group,
# extract the entries of that group
while true; do
    if [[ ! "$entry" == */ ]]; then
        details=$(echo ${pass} | keepassxc-cli show "${database}" "${entry}" 2> /dev/null | \
            eval $dmenu)
        break;
    else
        newentry=$(echo ${pass} | keepassxc-cli ls "${database}" "${entry}" 2> /dev/null | \
            eval $dmenu || exit)
        [[ $newentry ]] || exit
        entry=$entry$newentry
    fi
done

# Exit if nothing is selected
[[ $details ]] || exit

# Determines which field from details is selected 
field=$(echo "$details" | cut -d ':' -f 1)

# If the password field is selected, copy it safely to the clipboard and clear the
# clipboard after the specified timeout.
# If the selected field is not password. copy its contents to the clipboard
if [[ "$field" == "Password" ]]; then
    echo ${pass} | keepassxc-cli clip "${database}" "${entry}" > /dev/null
    notify-send "keepassxc" "Password copied to clipboard for ${timeout} seconds"
    sleep $timeout
    echo '' | xclip -sel clip

    # Remove entry from clipboard managers e.g. for copyq
    # copyq remove 0 2> /dev/null
else
    echo "$details" | cut -d ':' -f 2- | sed 's/\s//' | xclip -sel clip
    notify-send "keepassxc" "${field} copied to clipboard"
fi
