#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi


if [[ -f ~/.cache/passmenuprev ]] ; then
    PREVENTRY=$(cat ~/.cache/passmenuprev)
    PREVENTRYSHORT=$(grep -o -P '/.*(?=\/.*\/)\/\K.*' <<< $PREVENTRY)
fi
STARTDIR=$PASSWORD_STORE_DIR
BASEDIR=$STARTDIR
DONE=0
LEVEL=0
SELECTION=""

while [ "$DONE" -eq 0 ] ; do 
  password_files=( "$STARTDIR"/* )
  password_files=( "${password_files[@]#"$STARTDIR"/}" )
  password_files=( "${password_files[@]%.gpg}" )
  
  if [ "$LEVEL" -ne 0 ] ; then
    password_files=(".." "${password_files[@]}") 
  else
    password_files=("${password_files[@]}" "Previous entry - $PREVENTRYSHORT")
  fi
  entry=$(printf '%s\n' "${password_files[@]}" | dmenu "$@" -l 15)
  
  # echo "entry: $entry"
  if [ -z "$entry" ] ; then
    DONE=1
    exit
  fi

  if [ "$entry" != ".." ] ; then

    # check if previous entry was selected
    if [ "$entry" = "Previous entry - $PREVENTRYSHORT" ] ; then
        SELECTION="$PREVENTRY"
    else
      SELECTION="$SELECTION/$entry"
    fi
  
    # check if another dir
    if [ -d "$STARTDIR/$entry" ] ; then
      STARTDIR="$STARTDIR/$entry"
      LEVEL=$((LEVEL+1))
    else
      # not a directory so it must be a real password entry
  
      if [[ $typeit -eq 0 ]]; then
        notify-send --urgency=normal --expire-time=10000 "Password copied to clipboard!" "$(pass show "$SELECTION" | tail -n +2)\n"
        pass show -c "$SELECTION" > /dev/null
      else
        notify-send --urgency=normal --expire-time=10000 "Password copied to clipboard!" "$(pass show "$SELECTION" | tail -n +2)\n"
        # xdotool - <<<"type --clearmodifiers -- $(pass show "$SELECTION" | head -n 1)"
      fi
      DONE=1
    fi
  
  else
    LEVEL=$((LEVEL-1))
    # removes last slash and text from selection
    SELECTION=$(grep -o -P '/.*(?=\/)' <<< $SELECTION)
    STARTDIR="$BASEDIR/$SELECTION"
  fi
done
echo "$SELECTION" > ~/.cache/passmenuprev
echo "$SELECTION"
